# Generated by Django 4.1.7 on 2023-03-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('work_position', models.CharField(default='python developer', max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('salary', models.SmallIntegerField(default=3000)),
                ('reply', models.CharField(choices=[(1, 'Rejected'), (2, 'Accepted'), (3, 'Next Stage ')], default='Rejected', max_length=32)),
                ('reply_date', models.DateField()),
                ('other', models.TextField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompnyName', to='cv.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkPosition', to='cv.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
